# Generated by Django 5.1.2 on 2024-12-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_customuser_join_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('disability_type', models.CharField(blank=True, max_length=50, null=True)),
                ('cs_knowledge', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('cs_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('cs_level', models.CharField(blank=True, max_length=50, null=True)),
                ('cs_suggestion', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
        ),
    ]
