# Generated by Django 5.1.2 on 2024-12-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_question_answer_alter_question_question_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
