# Generated by Django 5.1.2 on 2024-12-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_roadmap_delete_track'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='useranswer',
        ),
    ]
