# Generated by Django 5.1.2 on 2024-12-22 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_remove_question_id_remove_question_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='next_question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='track_url',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answeredat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='answer',
            name='answerid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='userid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='useranswers',
        ),
    ]
