# Generated by Django 5.1.2 on 2024-12-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_remove_answer_answer_text_remove_answer_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
        migrations.AlterModelTable(
            name='questions',
            table=None,
        ),
    ]
