# Generated by Django 5.1.2 on 2025-01-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0007_rename_question_questions_alter_questions_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
