# Generated by Django 5.1.2 on 2025-01-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0009_alter_answer_answer_alter_answer_answeredat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
