# Generated by Django 5.1.3 on 2024-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
