# Generated by Django 5.1.3 on 2024-11-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_alter_question_answer_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
