# Generated by Django 5.1.3 on 2024-11-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_rename_answer_useranswer_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer_text',
            new_name='answer',
        ),
    ]
