# Generated by Django 5.1.2 on 2024-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_track_question_next_question_question_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_choices',
            new_name='explanation',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='question',
            name='options_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
