# Generated by Django 5.1.2 on 2024-12-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_result'),
        ('questionnaire', '0007_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.tracks'),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
