# Generated by Django 5.1.2 on 2024-12-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_delete_useranswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
