# Generated by Django 5.1.2 on 2024-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0010_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('trackid', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField()),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('next_question_id', models.IntegerField(blank=True, null=True)),
                ('course_name', models.TextField(blank=True, null=True)),
                ('q_level', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
