# Generated by Django 5.1.3 on 2024-11-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='http://example.com', max_length=255),
            preserve_default=False,
        ),
    ]
