# Generated by Django 5.1.2 on 2024-12-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_level_course_disability_type_answer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='useranswers',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
