# Generated by Django 5.1.2 on 2024-12-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_answer_table_alter_course_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
    ]
