# Generated by Django 5.1.2 on 2024-12-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
    ]
