# Generated by Django 5.1.2 on 2024-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_course_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False},
        ),
    ]
