# Generated by Django 5.1.2 on 2024-12-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_courses_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
