# Generated by Django 5.1.2 on 2024-12-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_courses_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField(default='http://example.com')),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('course_level', models.CharField(default='Beginner', max_length=50)),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.playlist'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
