# Generated by Django 5.1.2 on 2024-12-19 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_tracks_alter_playlist_options_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='courses.courses'),
        ),
    ]
