# Generated by Django 5.1.2 on 2024-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
