# Generated by Django 5.1.2 on 2024-12-21 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_courses_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='disability_type',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='playlist',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='video_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
