# Generated by Django 5.1.2 on 2024-12-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_rename_link_playlist_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='course_level',
        ),
        migrations.AddField(
            model_name='playlist',
            name='difficultylevel',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(default='1:00:00'),
        ),
    ]
