# Generated by Django 5.1.2 on 2024-12-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_playlist_course_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
