# Generated by Django 5.1.2 on 2025-01-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_delete_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='track',
            new_name='trackid',
        ),
    ]
