# Generated by Django 5.1.2 on 2025-01-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_playlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='trackid',
            field=models.ForeignKey(db_column='trackid', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.tracks'),
        ),
    ]
