# Generated by Django 5.1.2 on 2025-01-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_remove_courses_user_courses_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='created_at',
        ),
    ]
